### ISSUE TITLE
Invalid define-condition form leads to compilation failure on SBCL

### ISSUE THREAD

**Issue by quicklisp** [genovese/make-hash#1]
You have a define-condition form like this:

```
(define-condition foo () () (:default-initargs (:foo 42 :bar 85))
```

The default-initargs should be followed by the args directly, not a list of the args. SBCL now treats this as a compile-time error.

**Comment by genovese** [comment]
Thanks, Zach. I've fixed this and rerun the tests successfully on SBCL 1.1.6.
